import { ICategory } from '../models/Category';
import { IProduct } from '../models/Product';
import { ICombo } from '../models/Combo';
import { IBlogPost } from '../models/BlogPost';
import { IReview } from '../models/Review';

export const categories: Partial<ICategory>[] = [
  {
    name: 'Ghẹ Xanh',
    slug: 'ghe-xanh',
    icon: '🦀',
    description: 'Ghẹ xanh tươi sống đánh bắt hàng ngày',
  },
  {
    name: 'Ghẹ Đỏ',
    slug: 'ghe-do',
    icon: '🦀',
    description: 'Tuyển chọn ghẹ đỏ cao cấp',
  },
  {
    name: 'Ghẹ Sữa',
    slug: 'ghe-sua',
    icon: '🦀',
    description: 'Thịt ghẹ sữa mềm ngọt',
  },
  {
    name: 'Ghẹ Thịt',
    slug: 'ghe-thit',
    icon: '🦀',
    description: 'Ghẹ thịt đầy đặn, chắc nịch',
  },
  {
    name: 'Combo Noel Gia Đình',
    slug: 'combo-noel-gia-dinh',
    icon: '🎄',
    description: 'Gói combo đặc biệt dịp lễ',
  },
  {
    name: 'Hải Sản Khác',
    slug: 'hai-san-khac',
    icon: '🦐',
    description: 'Các loại hải sản tươi sống khác',
  },
];

export const products: Partial<IProduct>[] = [
  {
    name: 'Ghẹ Xanh Cao Cấp (1kg)',
    slug: 'ghe-xanh-cao-cap-1kg',
    type: 'crab',
    price: 450000,
    originalPrice: 550000,
    isOnSale: true,
    tags: ['ghẹ xanh', 'Noel', 'tươi sống', 'Bán chạy'],
    images: ['https://via.placeholder.com/400x300/1565C0/FFFFFF?text=Ghe+Xanh+1kg'],
    shortDescription: 'Ghẹ xanh tươi sống, đánh bắt hàng ngày, đảm bảo chất lượng',
    description: 'Ghẹ xanh tươi sống đánh bắt hàng ngày từ vùng biển Cà Mau, đảm bảo còn sống khi giao hàng. Thịt chắc, ngọt đậm đà, hoàn hảo cho các món hấp, rang me, nướng phô mai.',
    origin: 'Cà Mau',
    sizeOptions: [
      { label: 'Size S', value: 's' },
      { label: 'Size M', value: 'm' },
      { label: 'Size L', value: 'l' },
      { label: 'Size XL', value: 'xl' },
    ],
    weightOptions: [
      { label: '0.5kg', value: 0.5 },
      { label: '1kg', value: 1 },
      { label: '2kg', value: 2 },
    ],
    status: 'available',
    avgRating: 4.8,
    reviewCount: 124,
  },
  {
    name: 'Ghẹ Đỏ Tươi Sống (800g)',
    slug: 'ghe-do-tuoi-song-800g',
    type: 'crab',
    price: 380000,
    originalPrice: 450000,
    isOnSale: true,
    tags: ['ghẹ đỏ', 'Noel', 'tươi sống', 'Giảm Noel'],
    images: ['https://via.placeholder.com/400x300/E53935/FFFFFF?text=Ghe+Do+800g'],
    shortDescription: 'Ghẹ đỏ cao cấp, hoàn hảo cho dịp đặc biệt',
    description: 'Ghẹ đỏ tươi sống từ Phú Quốc, thịt đầy đặn, vị ngọt đậm đà. Hoàn hảo cho các món hấp, rang me, nướng phô mai.',
    origin: 'Phú Quốc',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 89,
  },
  {
    name: 'Ghẹ Sữa Tươi (1.2kg)',
    slug: 'ghe-sua-tuoi-1-2kg',
    type: 'crab',
    price: 520000,
    isOnSale: false,
    tags: ['ghẹ sữa', 'tươi sống', 'Mới'],
    images: ['https://via.placeholder.com/400x300/1E88E5/FFFFFF?text=Ghe+Sua+1.2kg'],
    shortDescription: 'Ghẹ sữa mềm ngọt, thịt đầy đặn',
    description: 'Ghẹ sữa tươi sống từ Bạc Liêu, thịt mềm ngọt, gạch đỏ tươi. Đặc biệt thơm ngon khi hấp hoặc nướng.',
    origin: 'Bạc Liêu',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 156,
  },
  {
    name: 'Ghẹ Thịt Cao Cấp (1kg)',
    slug: 'ghe-thit-cao-cap-1kg',
    type: 'crab',
    price: 480000,
    originalPrice: 580000,
    isOnSale: true,
    tags: ['ghẹ thịt', 'tươi sống', 'Bán chạy'],
    images: ['https://via.placeholder.com/400x300/FF3B3F/FFFFFF?text=Ghe+Thit+1kg'],
    shortDescription: 'Ghẹ thịt chắc, đầy đặn, vị ngọt đậm đà',
    description: 'Ghẹ thịt loại 1 từ Cà Mau, thịt chắc nịch, vị ngọt đậm đà. Hoàn hảo cho các món hấp, rang me, nướng phô mai.',
    origin: 'Cà Mau',
    status: 'available',
    avgRating: 4.6,
    reviewCount: 203,
  },
  {
    name: 'Ghẹ Hấp Sẵn',
    slug: 'ghe-hap-san',
    type: 'crab',
    price: 350000,
    originalPrice: 420000,
    isOnSale: true,
    tags: ['ghẹ hấp', 'đã chế biến', 'Giảm Noel'],
    images: ['https://via.placeholder.com/400x300/E53935/FFFFFF?text=Ghe+Hap+San'],
    shortDescription: 'Ghẹ hấp sẵn, chín đều, ăn ngay',
    description: 'Ghẹ đã hấp chín với bia và gừng, chín đều, thơm ngon. Ăn ngay hoặc hâm nóng lại.',
    origin: 'Đã chế biến',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 312,
  },
  {
    name: 'Ghẹ Nướng Bơ Tỏi',
    slug: 'ghe-nuong-bo-toi',
    type: 'crab',
    price: 420000,
    isOnSale: false,
    tags: ['ghẹ nướng', 'đã chế biến', 'Mới'],
    images: ['https://via.placeholder.com/400x300/1E88E5/FFFFFF?text=Ghe+Nuong+Bo'],
    shortDescription: 'Ghẹ nướng với sốt bơ tỏi thơm lừng',
    description: 'Ghẹ nướng với sốt bơ tỏi thơm lừng, thịt mềm ngọt, vị béo ngậy. Hoàn hảo cho bữa tiệc.',
    origin: 'Đã chế biến',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 178,
  },
  {
    name: 'Combo Canh Ghẹ',
    slug: 'combo-canh-ghe',
    type: 'combo',
    price: 280000,
    originalPrice: 350000,
    isOnSale: true,
    tags: ['canh ghẹ', 'đã chế biến', 'Bán chạy'],
    images: ['https://via.placeholder.com/400x300/1565C0/FFFFFF?text=Canh+Ghe'],
    shortDescription: 'Canh ghẹ nóng hổi, hoàn hảo cho mùa đông',
    description: 'Canh ghẹ nóng hổi với nước dùng ngọt thanh, thịt ghẹ tươi ngon. Hoàn hảo cho mùa đông.',
    origin: 'Đã chế biến',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 95,
  },
  {
    name: 'Combo Ghẹ Cao Cấp (2kg)',
    slug: 'combo-ghe-cao-cap-2kg',
    type: 'combo',
    price: 850000,
    originalPrice: 1050000,
    isOnSale: true,
    tags: ['combo ghẹ', 'Noel', 'Giảm Noel'],
    images: ['https://via.placeholder.com/400x300/E53935/FFFFFF?text=Combo+Ghe+2kg'],
    shortDescription: 'Tuyển chọn ghẹ cao cấp cho dịp đặc biệt',
    description: 'Combo tuyển chọn ghẹ cao cấp gồm ghẹ xanh, ghẹ đỏ, ghẹ sữa. Hoàn hảo cho dịp đặc biệt.',
    origin: 'Hỗn hợp',
    status: 'available',
    avgRating: 5.0,
    reviewCount: 67,
  },
  {
    name: 'Ghẹ Xanh Tươi Sống (1.5kg)',
    slug: 'ghe-xanh-tuoi-song-1-5kg',
    type: 'crab',
    price: 650000,
    originalPrice: 750000,
    isOnSale: true,
    tags: ['ghẹ xanh', 'tươi sống', 'Bán chạy'],
    images: ['https://via.placeholder.com/400x300/1565C0/FFFFFF?text=Ghe+Xanh+Song'],
    shortDescription: 'Ghẹ xanh tươi sống, đảm bảo còn sống khi giao hàng',
    description: 'Ghẹ xanh tươi sống size lớn, đảm bảo còn sống khi giao hàng. Thịt chắc, ngọt đậm đà.',
    origin: 'Cà Mau',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 142,
  },
  {
    name: 'Ghẹ Cà Ri Sẵn',
    slug: 'ghe-ca-ri-san',
    type: 'crab',
    price: 320000,
    originalPrice: 380000,
    isOnSale: true,
    tags: ['ghẹ cà ri', 'đã chế biến', 'Giảm Noel'],
    images: ['https://via.placeholder.com/400x300/FF3B3F/FFFFFF?text=Ghe+Ca+Ri'],
    shortDescription: 'Ghẹ cà ri cay nồng với nước cốt dừa',
    description: 'Ghẹ cà ri cay nồng với nước cốt dừa, thơm mùi lá chanh, vị chua cay ngọt hài hòa.',
    origin: 'Đã chế biến',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 201,
  },
  {
    name: 'Combo Hải Sản Tổng Hợp',
    slug: 'combo-hai-san-tong-hop',
    type: 'combo',
    price: 680000,
    originalPrice: 850000,
    isOnSale: true,
    tags: ['hải sản', 'combo', 'Mới'],
    images: ['https://via.placeholder.com/400x300/1E88E5/FFFFFF?text=Hai+San+Tong+Hop'],
    shortDescription: 'Hải sản tổng hợp gồm ghẹ, tôm, cá',
    description: 'Combo hải sản tổng hợp gồm ghẹ, tôm, cá tươi sống. Hoàn hảo cho bữa tiệc gia đình.',
    origin: 'Hỗn hợp',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 98,
  },
  {
    name: 'Chả Ghẹ (6 miếng)',
    slug: 'cha-ghe-6-mieng',
    type: 'crab',
    price: 250000,
    originalPrice: 300000,
    isOnSale: true,
    tags: ['chả ghẹ', 'đã chế biến', 'Bán chạy'],
    images: ['https://via.placeholder.com/400x300/E53935/FFFFFF?text=Cha+Ghe'],
    shortDescription: 'Chả ghẹ giòn rụm với sốt chấm đặc biệt',
    description: 'Chả ghẹ giòn rụm với sốt chấm đặc biệt, thịt ghẹ tươi ngon, vị ngọt đậm đà.',
    origin: 'Đã chế biến',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 167,
  },
];

export const combos: Partial<ICombo>[] = [
  {
    name: 'Combo Noel Gia Đình 4 Người',
    slug: 'combo-noel-gia-dinh-4-nguoi',
    products: [],
    price: 1200000,
    originalPrice: 1500000,
    description: 'Combo đặc biệt cho gia đình 4 người dịp Noel, gồm ghẹ xanh, ghẹ đỏ, ghẹ sữa và các món chế biến sẵn.',
    images: ['https://via.placeholder.com/400x300/E53935/FFFFFF?text=Combo+Noel+4'],
    tags: ['Noel', 'combo', 'gia đình'],
  },
  {
    name: 'Combo Hải Sản Tổng Hợp Premium',
    slug: 'combo-hai-san-tong-hop-premium',
    products: [],
    price: 1800000,
    originalPrice: 2200000,
    description: 'Combo hải sản tổng hợp premium với đầy đủ các loại ghẹ, tôm, cá cao cấp.',
    images: ['https://via.placeholder.com/400x300/1E88E5/FFFFFF?text=Combo+Premium'],
    tags: ['premium', 'combo', 'hải sản'],
  },
  {
    name: 'Combo Ghẹ Tươi Sống 2kg',
    slug: 'combo-ghe-tuoi-song-2kg',
    products: [],
    price: 850000,
    originalPrice: 1050000,
    description: 'Combo ghẹ tươi sống 2kg, tuyển chọn từ các loại ghẹ cao cấp nhất.',
    images: ['https://via.placeholder.com/400x300/1565C0/FFFFFF?text=Combo+2kg'],
    tags: ['ghẹ', 'tươi sống', 'combo'],
  },
];

export const blogPosts: Partial<IBlogPost>[] = [
  {
    title: '5 Món Ghẹ Cho Tiệc Noel',
    slug: '5-mon-ghe-cho-tiec-noel',
    excerpt: 'Khám phá những công thức ghẹ ngon nhất để gây ấn tượng với khách trong mùa lễ này. Từ ghẹ hấp cổ điển đến chả ghẹ đầy hương vị.',
    content: 'Nội dung chi tiết về 5 món ghẹ cho tiệc Noel...',
    thumbnail: 'https://via.placeholder.com/600x400/E53935/FFFFFF?text=5+Mon+Ghe+Noel',
    tags: ['Công Thức', 'Noel', 'Ghẹ'],
    publishedAt: new Date('2024-12-15'),
  },
  {
    title: 'Cách Bảo Quản Hải Sản Mùa Lạnh',
    slug: 'cach-bao-quan-hai-san-mua-lanh',
    excerpt: 'Học các kỹ thuật đúng cách để bảo quản ghẹ và hải sản tươi trong những tháng mùa đông để duy trì độ tươi và chất lượng.',
    content: 'Nội dung chi tiết về cách bảo quản hải sản mùa lạnh...',
    thumbnail: 'https://via.placeholder.com/600x400/1565C0/FFFFFF?text=Bao+Quan+Hai+San',
    tags: ['Mẹo Vặt', 'Bảo Quản'],
    publishedAt: new Date('2024-12-10'),
  },
  {
    title: 'Hướng Dẫn Combo Hải Sản Noel',
    slug: 'huong-dan-combo-hai-san-noel',
    excerpt: 'Tất cả những gì bạn cần biết về combo hải sản Noel đặc biệt của chúng tôi. Hoàn hảo cho các buổi tụ tập gia đình và bữa tiệc lễ hội.',
    content: 'Nội dung chi tiết về combo hải sản Noel...',
    thumbnail: 'https://via.placeholder.com/600x400/E53935/FFFFFF?text=Huong+Dan+Combo+Noel',
    tags: ['Hướng Dẫn', 'Combo', 'Noel'],
    publishedAt: new Date('2024-12-08'),
  },
  {
    title: 'Lợi Ích Sức Khỏe Của Ghẹ Tươi',
    slug: 'loi-ich-suc-khoe-cua-ghe-tuoi',
    excerpt: 'Khám phá những lợi ích dinh dưỡng của thịt ghẹ tươi và tại sao nó là một bổ sung tuyệt vời cho chế độ ăn mùa đông của bạn.',
    content: 'Nội dung chi tiết về lợi ích sức khỏe của ghẹ tươi...',
    thumbnail: 'https://via.placeholder.com/600x400/1E88E5/FFFFFF?text=Loi+Ich+Suc+Khoe',
    tags: ['Sức Khỏe', 'Dinh Dưỡng'],
    publishedAt: new Date('2024-12-05'),
  },
  {
    title: 'Ý Tưởng Tiệc Hải Sản Mùa Đông',
    slug: 'y-tuong-tiec-hai-san-mua-dong',
    excerpt: 'Những ý tưởng sáng tạo để tổ chức một bữa tiệc hải sản mùa đông đáng nhớ. Mẹo về trình bày, kết hợp và tạo không khí hoàn hảo.',
    content: 'Nội dung chi tiết về ý tưởng tiệc hải sản mùa đông...',
    thumbnail: 'https://via.placeholder.com/600x400/FF3B3F/FFFFFF?text=Y+Tuong+Tiec+Hai+San',
    tags: ['Giải Trí', 'Tiệc'],
    publishedAt: new Date('2024-12-03'),
  },
];

export const reviews: Partial<IReview>[] = [
  {
    authorName: 'Nguyễn Văn A',
    rating: 5,
    comment: 'Ghẹ rất tươi, còn sống khi nhận hàng. Thịt chắc, ngọt đậm đà. Đóng gói cẩn thận, giữ lạnh tốt. Sẽ đặt lại!',
  },
  {
    authorName: 'Trần Thị B',
    rating: 5,
    comment: 'Lần đầu mua ghẹ online mà chất lượng tốt như vậy. Hấp bia ăn rất ngon, cả nhà đều khen. Giao hàng nhanh, đóng gói chuyên nghiệp.',
  },
  {
    authorName: 'Lê Văn C',
    rating: 4,
    comment: 'Ghẹ tươi, thịt đầy đặn. Có một vài con nhỏ hơn mong đợi nhưng nhìn chung chất lượng tốt. Giá cả hợp lý.',
  },
  {
    authorName: 'Phạm Thị D',
    rating: 5,
    comment: 'Tuyệt vời! Ghẹ size L đúng như mô tả, thịt rất chắc và ngọt. Rang me ăn ngon xuất sắc. Đóng gói giữ lạnh rất tốt, nhận hàng vẫn còn sống.',
  },
  {
    authorName: 'Hoàng Văn E',
    rating: 4,
    comment: 'Chất lượng tốt, giao hàng đúng hẹn. Ghẹ tươi, thịt ngon. Chỉ có điều giá hơi cao một chút nhưng đổi lại chất lượng đảm bảo.',
  },
  {
    authorName: 'Vũ Thị F',
    rating: 5,
    comment: 'Mua cho bữa tiệc Noel, ghẹ rất tươi và ngon. Khách hàng đều khen. Đóng gói đẹp, chuyên nghiệp. Cảm ơn shop!',
  },
];

