import { IProduct } from '../models/Product';

export interface SeedProduct extends Partial<IProduct> {
  categorySlug: string;
}

const img = (text: string) =>
  `data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="600" height="400"><defs><linearGradient id="g" x1="0" x2="1" y1="0" y2="1"><stop stop-color="%231565C0" offset="0%"/><stop stop-color="%23E53935" offset="100%"/></linearGradient></defs><rect width="600" height="400" fill="url(%23g)"/><text x="50%" y="50%" fill="white" font-size="28" font-family="Arial" text-anchor="middle" dominant-baseline="middle">${encodeURIComponent(text)}</text></svg>`;

export const sampleProducts: SeedProduct[] = [
  // Ghẹ sống
  {
    name: 'Ghẹ xanh sống size 4–6 con/kg',
    slug: 'ghe-xanh-song-4-6',
    categorySlug: 'ghe-song',
    type: 'crab',
    price: 520000,
    originalPrice: 580000,
    isOnSale: true,
    tags: ['ghẹ xanh', 'hấp bia', 'rang me'],
    images: [img('Ghẹ xanh sống'), img('Ghẹ hấp sả'), img('Ghẹ rang me')],
    shortDescription: 'Ghẹ xanh Cà Mau tươi sống, thịt chắc, gạch vàng, giao nhanh trong 2h nội thành.',
    description:
      'Ghẹ xanh tươi sống từ vùng biển Cà Mau, được bảo quản lạnh và giao trong 2 giờ. Thịt chắc, ngọt, phù hợp hấp sả, rang me hoặc nướng phô mai. Giàu protein, ít béo, tốt cho sức khỏe.',
    origin: 'Cà Mau',
    sizeOptions: [
      { label: 'Size 4–6 con/kg', value: '4-6' },
      { label: 'Size 3–4 con/kg', value: '3-4' },
    ],
    weightOptions: [
      { label: '1kg', value: 1 },
      { label: '2kg', value: 2 },
    ],
    status: 'available',
    avgRating: 4.8,
    reviewCount: 120,
  },
  {
    name: 'Ghẹ đỏ sống size đại',
    slug: 'ghe-do-song-size-dai',
    categorySlug: 'ghe-song',
    type: 'crab',
    price: 680000,
    originalPrice: 760000,
    isOnSale: true,
    tags: ['ghẹ đỏ', 'nướng phô mai', 'lẩu ghẹ'],
    images: [img('Ghẹ đỏ sống'), img('Ghẹ đỏ hấp'), img('Ghẹ đỏ lẩu')],
    shortDescription: 'Ghẹ đỏ size đại, gạch nhiều, thích hợp nướng phô mai hoặc lẩu ghẹ.',
    description:
      'Ghẹ đỏ Phan Thiết size đại, gạch nhiều, vị ngọt đậm đà. Thích hợp nướng phô mai, hấp bia hoặc chế biến lẩu ghẹ. Đóng gói giữ lạnh 0–4°C.',
    origin: 'Phan Thiết',
    sizeOptions: [
      { label: 'Size đại', value: 'xl' },
      { label: 'Size lớn', value: 'l' },
    ],
    weightOptions: [{ label: '1kg', value: 1 }],
    status: 'available',
    avgRating: 4.9,
    reviewCount: 86,
  },
  {
    name: 'Ghẹ gạch Cà Mau',
    slug: 'ghe-gach-ca-mau',
    categorySlug: 'ghe-song',
    type: 'crab',
    price: 750000,
    tags: ['ghẹ gạch', 'Cà Mau', 'đặc sản'],
    images: [img('Ghẹ gạch'), img('Ghẹ gạch hấp')],
    shortDescription: 'Ghẹ gạch đỏ au, béo, thơm, đặc sản Cà Mau.',
    description:
      'Ghẹ gạch đỏ au, béo, thơm, chắc thịt. Được chọn lọc từ ghe đánh bắt trong ngày, bảo quản lạnh chuẩn. Hấp sả hoặc rang me đều giữ được vị ngọt.',
    origin: 'Cà Mau',
    weightOptions: [
      { label: '0.8kg', value: 0.8 },
      { label: '1kg', value: 1 },
    ],
    status: 'available',
    avgRating: 4.7,
    reviewCount: 64,
  },
  // Tôm hùm
  {
    name: 'Tôm hùm bông 1–1.2kg/con',
    slug: 'tom-hum-bong-1-1-2',
    categorySlug: 'tom-hum',
    type: 'seafood',
    price: 1350000,
    originalPrice: 1500000,
    isOnSale: true,
    tags: ['tôm hùm', 'nướng bơ tỏi', 'BBQ'],
    images: [img('Tôm hùm bông'), img('Tôm hùm nướng'), img('Tôm hùm sashimi')],
    shortDescription: 'Tôm hùm bông size 1–1.2kg, thịt săn chắc, ngọt.',
    description:
      'Tôm hùm bông sống size 1–1.2kg, thịt săn chắc, ngọt, nhiều gạch. Phù hợp nướng bơ tỏi, hấp sả hoặc sashimi. Giàu protein và khoáng chất.',
    origin: 'Khánh Hòa',
    weightOptions: [{ label: '1–1.2kg/con', value: 1 }],
    status: 'available',
    avgRating: 4.9,
    reviewCount: 98,
  },
  {
    name: 'Tôm hùm xanh 0.8–1kg/con',
    slug: 'tom-hum-xanh-0-8-1',
    categorySlug: 'tom-hum',
    type: 'seafood',
    price: 980000,
    tags: ['tôm hùm xanh', 'hấp sả', 'lẩu hải sản'],
    images: [img('Tôm hùm xanh'), img('Tôm hùm hấp')],
    shortDescription: 'Tôm hùm xanh tươi sống, ngọt thịt, thích hợp lẩu, hấp.',
    description:
      'Tôm hùm xanh tươi sống, vị ngọt thanh, thịt chắc. Thích hợp hấp sả, lẩu hải sản hoặc nướng mọi. Đóng gói oxy giữ sống.',
    origin: 'Nha Trang',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 72,
  },
  // Tôm sú
  {
    name: 'Tôm sú tươi size 20–25 con/kg',
    slug: 'tom-su-20-25',
    categorySlug: 'tom-su',
    type: 'seafood',
    price: 360000,
    tags: ['tôm sú', 'nướng', 'hấp'],
    images: [img('Tôm sú tươi'), img('Tôm sú nướng')],
    shortDescription: 'Tôm sú tươi size 20–25 con/kg, nướng muối ớt cực ngon.',
    description:
      'Tôm sú tươi sống, size 20–25 con/kg. Vỏ mỏng, thịt ngọt, dai. Thích hợp nướng muối ớt, hấp bia hoặc rim me.',
    origin: 'Bạc Liêu',
    status: 'available',
    avgRating: 4.6,
    reviewCount: 55,
  },
  {
    name: 'Tôm sú size 10–12 con/kg',
    slug: 'tom-su-10-12',
    categorySlug: 'tom-su',
    type: 'seafood',
    price: 520000,
    tags: ['tôm sú', 'BBQ'],
    images: [img('Tôm sú size lớn')],
    shortDescription: 'Tôm sú size 10–12 con/kg, thích hợp BBQ ngoài trời.',
    description:
      'Tôm sú size đại 10–12 con/kg, thịt chắc, ngọt. Món nướng BBQ hoặc hấp sả đều tuyệt vời. Đóng gói đá gel giữ lạnh.',
    origin: 'Cà Mau',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 60,
  },
  // Cua biển
  {
    name: 'Cua gạch Cà Mau loại 1',
    slug: 'cua-gach-ca-mau-loai-1',
    categorySlug: 'cua-bien',
    type: 'crab',
    price: 640000,
    tags: ['cua gạch', 'Cà Mau'],
    images: [img('Cua gạch Cà Mau')],
    shortDescription: 'Cua gạch đỏ tươi, béo, thơm, đặc sản Cà Mau.',
    description:
      'Cua gạch loại 1, gạch đỏ, béo, thơm. Vị ngọt đậm, thích hợp hấp bia, rang me hoặc nướng mọi. Đảm bảo tươi sống.',
    origin: 'Cà Mau',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 88,
  },
  {
    name: 'Cua thịt Phan Thiết size lớn',
    slug: 'cua-thit-phan-thiet',
    categorySlug: 'cua-bien',
    type: 'crab',
    price: 520000,
    tags: ['cua thịt', 'thịt chắc'],
    images: [img('Cua thịt')],
    shortDescription: 'Cua thịt size lớn, thịt chắc, ngọt, phù hợp rang me.',
    description:
      'Cua thịt Phan Thiết size lớn, thịt chắc, ngọt, ít nước. Chế biến rang me, hấp sả, nướng mọi đều ngon.',
    origin: 'Phan Thiết',
    status: 'available',
    avgRating: 4.6,
    reviewCount: 47,
  },
  // Hàu
  {
    name: 'Hàu sữa Nha Trang 12 con',
    slug: 'hau-sua-nha-trang',
    categorySlug: 'hau-tuoi',
    type: 'seafood',
    price: 150000,
    tags: ['hàu sữa', 'nướng phô mai'],
    images: [img('Hàu sữa'), img('Hàu nướng phô mai')],
    shortDescription: 'Hàu sữa Nha Trang béo, tươi, giàu kẽm.',
    description:
      'Hàu sữa Nha Trang, béo, tươi, sạch. Giàu kẽm, tốt cho sức khỏe. Thích hợp nướng phô mai, ăn sống kèm chanh ớt.',
    origin: 'Nha Trang',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 52,
  },
  {
    name: 'Hàu nướng phô mai combo 20 con',
    slug: 'hau-nuong-pho-mai-20',
    categorySlug: 'hau-tuoi',
    type: 'seafood',
    price: 320000,
    tags: ['hàu nướng', 'tiệc'],
    images: [img('Hàu phô mai')],
    shortDescription: 'Combo 20 con hàu nướng phô mai, tiện lợi cho tiệc nhỏ.',
    description:
      'Combo 20 con hàu đã sơ chế kèm phô mai, chỉ cần nướng 8–10 phút. Phù hợp tiệc gia đình, BBQ cuối tuần.',
    origin: 'Vũng Tàu',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 40,
  },
  // Ngao nghêu sò
  {
    name: 'Nghêu trắng hấp sả 1kg',
    slug: 'ngheu-trang-1kg',
    categorySlug: 'ngao-ngheu-so',
    type: 'seafood',
    price: 95000,
    tags: ['nghêu', 'lẩu hải sản'],
    images: [img('Nghêu trắng')],
    shortDescription: 'Nghêu trắng tươi, sạch cát, phù hợp lẩu và hấp sả.',
    description:
      'Nghêu trắng tươi, đã nhả cát, vị ngọt thanh. Phù hợp nấu lẩu hải sản, hấp sả hoặc xào bơ tỏi.',
    origin: 'Bến Tre',
    status: 'available',
    avgRating: 4.5,
    reviewCount: 33,
  },
  {
    name: 'Sò điệp Nhật cồi to 500g',
    slug: 'so-diep-nhat-500g',
    categorySlug: 'ngao-ngheu-so',
    type: 'seafood',
    price: 260000,
    tags: ['sò điệp', 'nướng mỡ hành'],
    images: [img('Sò điệp')],
    shortDescription: 'Sò điệp Nhật cồi to, ngọt, nướng mỡ hành cực ngon.',
    description:
      'Sò điệp Nhật cồi to, thịt dày, ngọt. Món nướng mỡ hành, bơ tỏi hoặc xào rau củ đều hợp. Giàu protein, ít béo.',
    origin: 'Nhật Bản',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 44,
  },
  // Cá hồi
  {
    name: 'Phi lê cá hồi Nauy 500g',
    slug: 'phi-le-ca-hoi-500g',
    categorySlug: 'ca-hoi',
    type: 'seafood',
    price: 210000,
    tags: ['cá hồi', 'sashimi', 'omega-3'],
    images: [img('Phi lê cá hồi'), img('Sashimi cá hồi')],
    shortDescription: 'Phi lê cá hồi Nauy 500g, thịt cam, giàu Omega-3.',
    description:
      'Phi lê cá hồi Nauy, cắt sạch xương, thịt cam tươi, giàu Omega-3. Dùng làm sashimi, áp chảo, nấu súp kem đều ngon.',
    origin: 'Nauy',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 110,
  },
  {
    name: 'Lườn cá hồi Nauy 1kg',
    slug: 'luon-ca-hoi-1kg',
    categorySlug: 'ca-hoi',
    type: 'seafood',
    price: 180000,
    tags: ['lườn cá hồi', 'chiên giòn'],
    images: [img('Lườn cá hồi')],
    shortDescription: 'Lườn cá hồi Nauy nhiều mỡ, chiên giòn hoặc nướng giấy bạc.',
    description:
      'Lườn cá hồi Nauy, nhiều mỡ, thơm, phù hợp chiên giòn, nướng giấy bạc hoặc nấu lẩu. Cắt khúc tiện lợi.',
    origin: 'Nauy',
    status: 'available',
    avgRating: 4.6,
    reviewCount: 58,
  },
  // Cá biển cao cấp
  {
    name: 'Cá thu một nắng 500g',
    slug: 'ca-thu-mot-nang-500g',
    categorySlug: 'ca-bien-cao-cap',
    type: 'seafood',
    price: 165000,
    tags: ['cá thu', 'kho', 'nướng'],
    images: [img('Cá thu một nắng')],
    shortDescription: 'Cá thu một nắng, cắt khoanh, thích hợp kho hoặc nướng.',
    description:
      'Cá thu một nắng, cắt khoanh, vị ngọt đậm, không tanh. Kho tiêu, nướng muối ớt hoặc chiên sốt cà đều hợp.',
    origin: 'Quy Nhơn',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 61,
  },
  {
    name: 'Cá ngừ đại dương phi lê 1kg',
    slug: 'ca-ngu-dai-duong-1kg',
    categorySlug: 'ca-bien-cao-cap',
    type: 'seafood',
    price: 240000,
    tags: ['cá ngừ', 'áp chảo', 'sashimi'],
    images: [img('Cá ngừ đại dương')],
    shortDescription: 'Phi lê cá ngừ đại dương, áp chảo hoặc sashimi.',
    description:
      'Phi lê cá ngừ đại dương, thịt đỏ, giàu đạm. Áp chảo tái hoặc sashimi đều ngon. Đóng gói hút chân không.',
    origin: 'Bình Định',
    status: 'available',
    avgRating: 4.6,
    reviewCount: 48,
  },
  {
    name: 'Cá chim trắng 800g',
    slug: 'ca-chim-trang-800g',
    categorySlug: 'ca-bien-cao-cap',
    type: 'seafood',
    price: 190000,
    tags: ['cá chim', 'hấp xì dầu'],
    images: [img('Cá chim trắng')],
    shortDescription: 'Cá chim trắng 800g/con, thịt trắng, ít xương dăm.',
    description:
      'Cá chim trắng 800g/con, thịt trắng, ít xương dăm. Hấp xì dầu, chiên giòn hoặc nướng muối ớt đều ngon.',
    origin: 'Vũng Tàu',
    status: 'available',
    avgRating: 4.5,
    reviewCount: 36,
  },
  // Combo gia đình
  {
    name: 'Combo lẩu hải sản gia đình 4 người',
    slug: 'combo-lau-hai-san-4-nguoi',
    categorySlug: 'combo-gia-dinh',
    type: 'combo',
    price: 890000,
    originalPrice: 990000,
    isOnSale: true,
    tags: ['combo', 'lẩu hải sản', 'gia đình'],
    images: [img('Combo lẩu 4 người')],
    shortDescription: 'Combo lẩu hải sản cho 4 người: ghẹ, tôm, mực, nghêu.',
    description:
      'Combo gồm ghẹ xanh 1kg, tôm sú 0.5kg, mực lá 0.5kg, nghêu 1kg, nước lẩu tomyum. Đủ cho 4 người, chế biến nhanh.',
    origin: 'Hỗn hợp',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 75,
  },
  {
    name: 'Combo BBQ hải sản ngoài trời',
    slug: 'combo-bbq-hai-san',
    categorySlug: 'combo-gia-dinh',
    type: 'combo',
    price: 1290000,
    originalPrice: 1450000,
    isOnSale: true,
    tags: ['combo', 'BBQ', 'ngoài trời'],
    images: [img('Combo BBQ')],
    shortDescription: 'Combo BBQ gồm tôm hùm xanh, sò điệp, hàu, cá hồi.',
    description:
      'Combo BBQ: tôm hùm xanh 1 con ~1kg, sò điệp Nhật 500g, hàu sữa 1kg, phi lê cá hồi 500g, nước sốt bơ tỏi.',
    origin: 'Hỗn hợp',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 82,
  },
  {
    name: 'Combo ghẹ – tôm – hàu cuối tuần',
    slug: 'combo-ghe-tom-hau',
    categorySlug: 'combo-gia-dinh',
    type: 'combo',
    price: 980000,
    originalPrice: 1100000,
    isOnSale: true,
    tags: ['combo', 'cuối tuần'],
    images: [img('Combo cuối tuần')],
    shortDescription: 'Ghẹ xanh 1kg, tôm sú 1kg, hàu sữa 1kg, sẵn sàng cho tiệc.',
    description:
      'Combo gồm ghẹ xanh 1kg, tôm sú 1kg, hàu sữa 1kg. Phù hợp tiệc 4–6 người, chế biến hấp, nướng hoặc lẩu.',
    origin: 'Hỗn hợp',
    status: 'available',
    avgRating: 4.7,
    reviewCount: 54,
  },
  // Khuyến mãi Noel
  {
    name: 'Ghẹ xanh Noel giảm 15%',
    slug: 'ghe-xanh-noel',
    categorySlug: 'khuyen-mai-noel',
    type: 'crab',
    price: 510000,
    originalPrice: 600000,
    isOnSale: true,
    tags: ['khuyến mãi', 'Noel'],
    images: [img('Ghẹ Noel')],
    shortDescription: 'Ghẹ xanh tươi sống, ưu đãi mùa Noel.',
    description:
      'Ghẹ xanh tươi sống, giao nhanh 2h nội thành, giảm 15% mùa Noel. Thịt chắc, ngọt, phù hợp hấp sả, rang me.',
    origin: 'Cà Mau',
    status: 'available',
    avgRating: 4.8,
    reviewCount: 92,
  },
  {
    name: 'Tôm hùm bông Noel combo 2 con',
    slug: 'tom-hum-bong-noel-2',
    categorySlug: 'khuyen-mai-noel',
    type: 'seafood',
    price: 2500000,
    originalPrice: 2800000,
    isOnSale: true,
    tags: ['khuyến mãi', 'tôm hùm'],
    images: [img('Tôm hùm Noel')],
    shortDescription: 'Combo 2 con tôm hùm bông size 1kg, ưu đãi Noel.',
    description:
      'Combo 2 con tôm hùm bông size ~1kg/con, ưu đãi Noel. Thích hợp nướng bơ tỏi, hấp hoặc sashimi.',
    origin: 'Khánh Hòa',
    status: 'available',
    avgRating: 4.9,
    reviewCount: 70,
  },
];
